### ISSUE TITLE
unclear documentation....

### ISSUE THREAD

**Issue by davidbuzz** [Ebiroll/esp32_blackmagic#1]
Is this designed to be flashed to a 'stock' blackmagic board so you can debug an 'esp32' as the target device, or is this designed to be flashed to an esp32 so it acts like a blackmagic board and allows you to debug ARM devices as the target..?

**Comment by Ebiroll** [comment]
It is a blackmagic board. It gives you possibility to debug an ARM board with SWD pins. No support for jtag. The main advantage over a regular black magic board is the wifi connection.
You need to install this to compile https://github.com/espressif/esp-idf
