### ISSUE TITLE
Think about a mechanism to sync with BMP

### ISSUE THREAD

**Issue by UweBonnes** [Ebiroll/esp32_blackmagic#2]
Hello,

it seems you simply imported the target directory. So your port misses a lot of target enhancements. A way to get into sycn with BMP would be nice, so that BMP user experience on the ESP is similar to the Native/PC-Hosted BMPs.

**Comment by Ebiroll** [comment]
Yes. I would like that. The problem has been the build system. With the new CMake build system, it should be possible.
https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/idf_as_lib

**Comment by Ebiroll** [comment]
It was not so difficult to create a proper cmake file. It compiles but remains to be tested. I used latest version of esp-idf.
https://github.com/Ebiroll/blackmagic
When tested I will create a pull request.

**Comment by Ebiroll** [comment]
I have tested and updated the repsitory to the latest version, and it works now.
Should I make a pull request? Maybe some more code cleanup? Anyway using bmp over wifi is nice. Here is a log of an swdp_scan.
7633053-7635333 SWD: : LINERESET
7635333-7635546 SWD: : JTAG->SWD
7635563-7636316 SWD: : LINERESET
7636548-7636648 SWD: : IDCODE
7638726-7638827 SWD: : OK
7638837-7639336 SWD: : 0x2ba01477
7640453-7640552 SWD: : R CTRL/STAT
7640681-7640702 SWD: : OK
7640713-7641168 SWD: : 0xf0000040
7641772-7641872 SWD: : W ABORT
7642000-7642021 SWD: : OK
7642190-7642553 SWD: : 0x00000000
7643308-7643408 SWD: : R CTRL/STAT
7643695-7643716 SWD: : OK
7643727-7644064 SWD: : 0xf0000040
7644510-7644610 SWD: : W CTRL/STAT
7644818-7644839 SWD: : OK
7644890-7645251 SWD: : 0xf0000040
7645620-7645719 SWD: : R CTRL/STAT
7646007-7646029 SWD: : OK
7646039-7646376 SWD: : 0xf0000040
7646781-7646881 SWD: : W CTRL/STAT
7647089-7647110 SWD: : OK
7647161-7647522 SWD: : 0xf4000040
7648001-7648100 SWD: : R CTRL/STAT
7648117-7648145 SWD: : ERROR
7648759-7649159 SWD: : RDBUFF
7649317-7649345 SWD: : ERROR
7650050-7650596 SWD: : W AP8
7650617-7650646 SWD: : OK
7650947-7651285 SWD: : 0x60000603
7651296-7651296 SWD: : 01
7651307-7651854 SWD: : R AP8
7651875-7651903 SWD: : OK
7651917-7652525 SWD: : 0x80000806
7652565-7653111 SWD: : W AP8
7653132-7653161 SWD: : OK
7653462-7653800 SWD: : 0x60000603
7653811-7653811 SWD: : 01
7653822-7654369 SWD: : R AP8
7654390-7654418 SWD: : OK
7654432-7655040 SWD: : 0x80000806
7655080-7655626 SWD: : W AP8
7655647-7655676 SWD: : OK

**Comment by Ebiroll** [comment]
I will create a pull request when it compiles and is tested on the esp32s2 as well.
